version: "3.8"

services:
  vs-frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - vs-backend
  vs-backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "8000:8000"
